<?php

namespace Slimdic\Test\Controller;

use Slimdic\Controller\AbstractController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-09 at 20:20:42.
 */
class AbstractControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * This test checks that the class is abstract
     */
    public function testCannotInstantiateAbstractController()
    {
        $refl = new \ReflectionClass('\Slimdic\Controller\AbstractController');
        $this->assertTrue($refl->isAbstract());
    }
}
